[[constraint]]
  name = "github.com/Financial-Times/service-status-go"
  version = "0.1.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.3.0"
  
[[override]]
  name = "github.com/Financial-Times/neo-model-utils-go"
  version = "0.4.0"

[prune]
  go-tests = true
  unused-packages = true

